#' Parse a namespace
#'
#' Parses a NAMESPACE file from a package into a tabular format.
#' @param path The path to the source code of a package.
#' @param package The name of a package available on CRAN.
#' @name parse_namespace
NULL

#' @describeIn parse_namespace Parses a local name space.
#' @export
#' @examples
#' random_dir <- tempdir()
#' pkg_dir <- file.path(random_dir, "randompkg")
#' dir.create(pkg_dir)
#' enc::write_lines_enc(c(
#'   "# Generated by roxygen2: do not edit by hand",
#'   "",
#'   "export(parse_cran_namespace)",
#'   "export(parse_local_namespace)",
#'   "import(gh)",
#'   "import(tibble)",
#'   "importFrom(magrittr,\"%>%\")",
#'   "importFrom(purrr,map_chr)",
#'   "importFrom(purrr,partial)"
#' ), file.path(pkg_dir, "NAMESPACE"))
#' parse_local_namespace(pkg_dir)
#' unlink(random_dir)
parse_local_namespace <- function(path = ".") {
  raw_namespace <- enc::read_lines_enc(file.path(path, "NAMESPACE"))
  parsed_namespace <- parse_namespace_into_tabular(raw_namespace)
  parsed_namespace
}

#' @describeIn parse_namespace Parses a namespace from the GitHub cran mirror.
#' @examples
#' parse_cran_namespace("tibble")
#' parse_cran_namespace("styler", ref = "1.0.0")
#' @export
parse_cran_namespace <- function(package, ...) {
  raw_namespace <- fetch_gh_content("cran", package, "NAMESPACE", ...)
  parsed_namespace <- parse_namespace_into_tabular(raw_namespace)
  parsed_namespace
}

#'
#' @importFrom desc description
parse_cran_description <- function(package) {
  raw_desc <- fetch_gh_content("cran", package, "DESCRIPTION")
  namespace <- description$new(text = desc)$get_deps() %>%
    add_column(object = NA)
  namespace$version <- NULL
  namespace
}

#' Write out minimal dependencies from a tabular namespace
#'
#' @param path The path to the source package for which DESCRIPTION should be
#'   adapted.
#' @param namespace A name space in a tabular format, i.e. a data frame with
#'   two columns `package` and `object` to be written to a file. If `NULL`,
#'   [collect_minimal_dependencies()] will be used to obtain the information
#'   necessary.
#' @importFrom purrr pmap
#' @export
write_minimal_dependencies <- function(path = ".", namespace = NULL) {
  if (is.null(namespace)) {
    namespace <- collect_minimal_dependencies(path)
  }
  pmap(namespace, set_dependency)
}

#' @importFrom desc desc_set_dep
set_dependency <- function(package, object, first_release) {
  desc_set_dep(
    package = package,
    type = "Imports",
    version = as_minimal_version(first_release)
  )
}

as_minimal_version <- function(x) {
  paste(">=", x)
}
